### ISSUE TITLE
Https redirection with one server

### ISSUE THREAD

**Issue by MrHash** [blacklabelops/nginx#17]
I'm not 100% certain on the behaviour but it seems to me like the `NGINX_REDIRECT_PORT80` setting is not effective with a single server definition e.g.:

```
NGINX_REDIRECT_PORT80: "true"
SERVER1REVERSE_PROXY_LOCATION1: /
SERVER1REVERSE_PROXY_PASS1: http://nginx:8000
SERVER1HTTP_ENABLED: "false"
SERVER1HTTPS_ENABLED: "true"
SERVER1PROXY_APPLICATION: custom
SERVER1REVERSE_PROXY_HEADER1FIELD1: X-Forwarded-Host killer.app
SERVER1REVERSE_PROXY_HEADER1FIELD2: X-Forwarded-Proto https
SERVER1REVERSE_PROXY_HEADER1FIELD3: X-Forwarded-For $$proxy_add_x_forwarded_for
```

**Comment by blacklabelops** [comment]
I will check this issue!

**Comment by blacklabelops** [comment]
Fixed in version 2.2 and latest.

**Comment by blacklabelops** [comment]
The generated config for port redirection had been directly deleted by the next operation. Must have been a mistake when making version 2.2 where i moved the generated config to folder /etc/nginx

**Comment by MrHash** [comment]
Hey looks like i'm still getting some strangeness on my side with latest tag. Looking into it some more.. suspect a bug in https://github.com/blacklabelops/nginx/blob/master/imagescripts/port_redirect.sh - may need to reopen

**Comment by blacklabelops** [comment]
I will recheck.

**Comment by blacklabelops** [comment]
Hello Hash,

I rechecked the development tag and the issue seems fixed. This fix won't be available on the latest tag until version 2.2 is released.

**Comment by MrHash** [comment]
Hey thanks for the recheck. Could you just clarify what is happening in the port redirect script at https://github.com/blacklabelops/nginx/blob/master/imagescripts/port_redirect.sh#L16-L18 please? It seems to me that if the server name is not assigned then there is no effective redirect.

**Comment by blacklabelops** [comment]
That's the loop-end check for enumerated variables. You never know how many envs of the kind `SERVER1..., SERVER2..., SERVER3.. ` there really are. So I start to enumerate env-variable names and check if there is actually an env variable with the given name. If this does not work for you then:

- You did not enumerate 
Or
- I did check an env that you actually do not use in your context

Maybe `SERVER_NAME`is not the always required env variable. Which one should I check?

**Comment by MrHash** [comment]
Ok I am not using a `SERVER1SERVER_NAME` setting in my configuration so maybe that's why?

**Comment by blacklabelops** [comment]
yes
